- shell: /bin/bash -c 'echo "Populating the /etc/hosts files..." > {{ fifo }}'

- name: build /etc/hosts file
  lineinfile:
          dest: /etc/hosts
          regexp: ".*\ {{ item.value.hostname }}.{{ domain_name }}.*"
          line: "{{ item.value.ip }} {{ item.value.hostname }} {{ item.value.hostname }}.{{ domain_name }}"
          state: present
  with_dict: '{{ nodeInfo }}'
