---
- hosts: gluster_nodes
  name: "Bootstrap HPE Apollo 4200 nodes for RHS One - General-purpose NAS flavor"

  become: true

  vars:
    current_user: "{{ansible_user|default(lookup('env', 'USER')) }}"
    disks:
      sdb:
        host: "RAID bus controller: Hewlett-Packard Company Smart Array Gen9 Controllers (rev 01)"
        model: "LOGICAL VOLUME"
        vendor: "HP"
        size: "9.10 TB"
      sdc:
        host: "RAID bus controller: Hewlett-Packard Company Smart Array Gen9 Controllers (rev 01)"
        model: "LOGICAL VOLUME"
        vendor: "HP"
        size: "9.10 TB"
      nvme0n1:
        host: "Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)"
        model: "MT0800KEXUU"
        vendor: null
        size: "745.21 GB"
      nvme1n1:
        host: "Non-Volatile memory controller: Intel Corporation PCIe Data Center SSD (rev 01)"
        model: "MT0800KEXUU"
        vendor: null
        size: "745.21 GB"
    raid_template: customize-hpe-apollo-gen9-nas-raid.j2

  tasks:
    # First check common requirements for this platform
    - include: customize-hpe-apollo-gen9-common.yml

    # Any checks specific to the GP-NAS flavor go here

...
